general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 5 min sin actividad: apagar pantallas
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 6 min sin actividad: bloquear
listener {
    timeout = 360
    on-timeout = loginctl lock-session
}

# 30 min: suspend
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
