###################
### AUTOSTART   ###
###################

# Protocolos y Plugins
exec-once = hyprctl plugin load ~/.config/hypr/plugins/hyprexpo.so
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Estética y UI
exec-once = ~/.config/hypr/scripts/gtk.sh
exec-once = swww-daemon && ~/.config/hypr/wallpaper.sh
exec-once = ~/.config/hypr/scripts/bar-switch.sh waybar
exec-once = swaync

# Utilidades del Sistema
exec-once = arch-update --tray
exec-once = hypridle
exec-once = hyprswitch init --show-title --custom-css ~/.config/hyprswitch/style.css &
exec-once = ~/.config/hypr/hotcorner.sh
exec-once = eww daemon && eww open clock && eww open sidebar
# exec-once = eww open sysinfo

# Gestión de Portapapeles
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
