####################
### INPUT & MISC ###
####################

# Dispositivos de Entrada (Teclado y Ratón)
input {
    kb_layout = latam
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = false
    }
}

# Comportamiento de Layout (Dwindle y Master)
dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

# Otros Ajustes (Logo, Splash, VFR)
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vfr = true
}
