###################
###   PLUGINS   ###
###################

# HyprExpo: Una vista general de los espacios de trabajo (similar a GNOME o macOS)
plugin:hyprexpo {
    columns = 3
    gap_size = 8
    bg_col = rgb(1e1e2e)
    workspace_method = center current
    enable_gesture = false
}

# HyprFocus: animación al cambiar el foco entre ventanas
plugin:hyprfocus {
    mode                   = slide
    only_on_monitor_change = false
    slide_height           = 8
}
