######################
### WINDOW RULES   ###
######################

# Reglas Generales
windowrule {
    name = suppress-maximize
    match:class = .*
    suppress_event = maximize
}

# Ventanas Flotantes (Utilidades)
windowrule {
    name = float-pavucontrol
    match:class = pavucontrol
    float = yes
    center = yes
}
windowrule {
    name = float-nm
    match:class = nm-connection-editor
    float = yes
    center = yes
}
windowrule {
    name = float-blueman
    match:class = blueman-manager
    float = yes
    center = yes
}
windowrule {
    name = float-settings
    match:title = Preferencias
    float = yes
    center = yes
}
windowrule {
    name = float-config
    match:title = Configuración
    float = yes
    center = yes
}

# Rofi Blur
blurls = rofi

# Herramientas Especiales
windowrule {
    name = flameshot
    match:class = flameshot
    float = yes
    move = 0 0
    pin = yes
}

# ML4W Calendar
windowrule {
    name = ml4w-calendar
    match:class = (com.ml4w.calendar)
    float = true
    move = monitor_w*0.5-window_w*0.5 76
    pin = true
    size = 400 400
}

# Aplicaciones de IA
windowrule {
    name = ai-webapps
    match:class = webapp-.*
    float = yes
    size = 1000 700
    center = yes
}

