# AUTOGENERATED — DO NOT EDIT

background {{bg}}
foreground {{fg}}

selection_background {{accent}}
selection_foreground {{bg}}

cursor {{accent}}
cursor_text_color {{bg}}

url_color {{accent}}

active_border_color {{accent}}
inactive_border_color {{surface2}}

# Normal
color0  {{bg}}
color1  {{red}}
color2  {{green}}
color3  {{yellow}}
color4  {{blue}}
color5  {{magenta}}
color6  {{cyan}}
color7  {{fg}}

# Bright
color8  {{surface}}
color9  {{red}}
color10 {{green}}
color11 {{yellow}}
color12 {{blue}}
color13 {{magenta}}
color14 {{cyan}}
color15 {{fg}}
